; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0

lib_ldf_mode = deep+

lib_deps =
    eModbus@^1.7.4
    AsyncTCP@^1.1.1

build_flags =
    -DCORE_DEBUG_LEVEL=3 -DBOARD=2

[env:esp32s2mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino

monitor_speed = 115200
upload_speed = 460800

; S2-nél gyakran natív USB van:
upload_port = /dev/serial/by-id/usb-WEMOS.CC_LOLIN-S2-MINI_0-if00
monitor_port = /dev/serial/by-id/usb-WEMOS.CC_LOLIN-S2-MINI_0-if00

lib_ldf_mode = deep+

lib_deps =
    eModbus@^1.7.4
    AsyncTCP@^1.1.1

build_flags =
    -DCORE_DEBUG_LEVEL=3 -DBOARD=1